{
  # =========================================================
  # NixOS Raspberry Pi 4 — Flake Definition
  # =========================================================
  # This file is the entry point for the entire build.
  # It declares:
  #   1. Where to get our dependencies (inputs)
  #   2. What we produce (outputs) — a NixOS system config
  #      and an SD card image
  # =========================================================

  description = "NixOS Raspberry Pi 4 SD card image";

  # ------- Inputs -------
  # These are the external dependencies our build needs.
  # Think of them like package.json dependencies, but for
  # an entire operating system.
  inputs = {
    # nixpkgs is THE repository of all Nix packages and
    # NixOS modules. We pin to the 24.11 stable release.
    # The "github:" prefix tells Nix to fetch it from GitHub.
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.11";
  };

  # ------- Outputs -------
  # This function receives the resolved inputs and produces
  # our build artifacts.
  outputs = { self, nixpkgs }: {

    # Define a NixOS system configuration called "rpi"
    nixosConfigurations.rpi = nixpkgs.lib.nixosSystem {

      # Target architecture: 64-bit ARM Linux
      # This matches the Raspberry Pi 4's CPU
      system = "aarch64-linux";

      # Modules are the building blocks of a NixOS config.
      # Each module can define system options, services,
      # packages, etc. They get merged together.
      modules = [

        # This is a built-in NixOS module that knows how to
        # produce an SD card image for aarch64 devices like
        # the Raspberry Pi. It sets up:
        #   - The correct partition layout (boot + root)
        #   - The extlinux bootloader (instead of GRUB)
        #   - Kernel and device tree for ARM boards
        #   - An auto-resizing root filesystem
        "${nixpkgs}/nixos/modules/installer/sd-card/sd-image-aarch64.nix"

        # Our main system configuration
        ./configuration.nix

        # Local/personal settings (generated by build.sh)
        # Contains: hostname, username, WiFi creds, SSH key
        ./local-config.nix
      ];
    };

    # Convenience alias so we can run:
    #   nix build .#sdImage
    # instead of the much longer:
    #   nix build .#nixosConfigurations.rpi.config.system.build.sdImage
    packages.aarch64-linux.sdImage =
      self.nixosConfigurations.rpi.config.system.build.sdImage;
  };
}
