# =========================================================
# LOCAL CONFIGURATION — Reads values from config.json
# =========================================================
# This file is safe to commit to Git. It contains NO secrets.
# All personal/secret values come from config.json, which is
# gitignored and generated by build.sh.
# =========================================================

{
  config,
  pkgs,
  lib,
  ...
}:

let
  # builtins.fromJSON reads a JSON string and returns a Nix
  # attribute set (like a dictionary/object). This happens
  # at build time, not at runtime on the Pi.
  #
  # Nix flakes only allow access to Git-tracked files. Since
  # config.json contains secrets and is gitignored, we use
  # the NIX_CONFIG_DIR environment variable (set by build.sh)
  # to locate it. This requires the --impure flag on nix build,
  # which is the standard escape hatch for flakes that need
  # to read untracked files.
  configPath =
    let
      p = builtins.getEnv "NIXOS_PI_CONFIG";
    in
    if p == "" then
      builtins.throw "NIXOS_PI_CONFIG env var is not set. Run: NIXOS_PI_CONFIG=/path/to/config.json nix build --impure"
    else
      p;
  cfg = builtins.fromJSON (builtins.readFile configPath);
in
{
  # -- Hostname --
  networking.hostName = cfg.hostname;

  # -- User account --
  users.users.${cfg.username} = {
    isNormalUser = true;

    # "wheel" grants sudo access
    # "networkmanager" allows managing WiFi connections
    extraGroups = [
      "wheel"
      "networkmanager"
    ];

    # Your SSH public key — this is how you'll log in.
    # Password auth is disabled in configuration.nix,
    # so this key is the ONLY way to access the Pi.
    openssh.authorizedKeys.keys = [ cfg.sshPubKey ];
  };

  # Allow members of "wheel" group to use sudo without a password.
  # Since we disabled password auth, you wouldn't be able to type
  # a sudo password anyway. This is standard for key-only setups.
  security.sudo.wheelNeedsPassword = false;

  # -- WiFi Configuration --
  # NetworkManager uses connection profiles to store WiFi settings.
  # This creates a profile that will auto-connect on boot.
  networking.networkmanager.ensureProfiles.profiles = {
    home-wifi = {
      connection = {
        id = cfg.wifi.ssid;
        type = "wifi";
        autoconnect = true;
        autoconnect-priority = 100;
      };
      wifi = {
        ssid = cfg.wifi.ssid;
        mode = "infrastructure";
      };
      wifi-security = {
        key-mgmt = "wpa-psk";
        psk = cfg.wifi.password;
      };
      ipv4 = {
        method = "auto"; # DHCP
      };
      ipv6 = {
        method = "auto";
      };
    };
  };
}
