# =========================================================
# LOCAL CONFIGURATION — Reads values from config.json
# =========================================================
# This file is safe to commit to Git. It contains NO secrets.
# All personal/secret values come from config.json, which is
# gitignored and generated by build.sh.
# =========================================================

{ config, pkgs, lib, ... }:

let
  # builtins.fromJSON reads a JSON string and returns a Nix
  # attribute set (like a dictionary/object). This happens
  # at build time, not at runtime on the Pi.
  #
  # We use an absolute path string ("/path/to/config.json")
  # instead of a Nix path (./config.json) because Nix flakes
  # only see files tracked by Git. Since config.json is
  # gitignored (it contains secrets), a Nix path would fail.
  # An absolute path string bypasses Git tracking entirely.
  dir = builtins.toString ./.;
  cfg = builtins.fromJSON (builtins.readFile "${dir}/config.json");
in
{
  # -- Hostname --
  networking.hostName = cfg.hostname;

  # -- User account --
  users.users.${cfg.username} = {
    isNormalUser = true;

    # "wheel" grants sudo access
    # "networkmanager" allows managing WiFi connections
    extraGroups = [ "wheel" "networkmanager" ];

    # Your SSH public key — this is how you'll log in.
    # Password auth is disabled in configuration.nix,
    # so this key is the ONLY way to access the Pi.
    openssh.authorizedKeys.keys = [ cfg.sshPubKey ];
  };

  # Allow members of "wheel" group to use sudo without a password.
  # Since we disabled password auth, you wouldn't be able to type
  # a sudo password anyway. This is standard for key-only setups.
  security.sudo.wheelNeedsPassword = false;

  # -- WiFi Configuration --
  # NetworkManager uses connection profiles to store WiFi settings.
  # This creates a profile that will auto-connect on boot.
  networking.networkmanager.ensureProfiles.profiles = {
    home-wifi = {
      connection = {
        id = cfg.wifi.ssid;
        type = "wifi";
        autoconnect = true;
        autoconnect-priority = 100;
      };
      wifi = {
        ssid = cfg.wifi.ssid;
        mode = "infrastructure";
      };
      wifi-security = {
        key-mgmt = "wpa-psk";
        psk = cfg.wifi.password;
      };
      ipv4 = {
        method = "auto";  # DHCP
      };
      ipv6 = {
        method = "auto";
      };
    };
  };
}
