# =========================================================
# LOCAL CONFIGURATION — Reads values from config.json
# =========================================================
# This file is safe to commit to Git. It contains NO secrets.
# All personal/secret values come from config.json, which is
# gitignored and generated by build.sh.
#
# Build with:
#   NIXOS_PI_CONFIG=/path/to/config.json nix build --impure
# =========================================================

{
  config,
  pkgs,
  lib,
  ...
}:

let
  # builtins.getEnv reads an environment variable at evaluation
  # time. Flakes normally disallow this (pure evaluation), so
  # we require --impure on the nix build command. This is the
  # standard escape hatch for secrets that shouldn't be in Git.
  configPath =
    let
      p = builtins.getEnv "NIXOS_PI_CONFIG";
    in
    if p == "" then
      builtins.throw "NIXOS_PI_CONFIG is not set. Run: NIXOS_PI_CONFIG=/path/to/config.json nix build --impure"
    else
      p;

  # Parse the JSON file into a Nix attribute set at build time.
  # cfg.wifi is a list of { ssid, password } objects.
  cfg = builtins.fromJSON (builtins.readFile configPath);
in
{
  # -- Home-manager global settings --
  # useGlobalPkgs: share the system nixpkgs with home-manager (avoids a
  #   second nixpkgs evaluation and keeps package versions consistent).
  # useUserPackages: install user packages into /etc/profiles rather than
  #   ~/.nix-profile, which works better with non-bash login shells.
  home-manager.useGlobalPkgs = true;
  home-manager.useUserPackages = true;

  # -- Hostname --
  networking.hostName = cfg.hostname;

  # -- User account --
  users.users.${cfg.username} = {
    isNormalUser = true;

    # "wheel" grants sudo access
    # "networkmanager" allows managing WiFi connections
    extraGroups = [
      "wheel"
      "networkmanager"
      "docker"
    ];

    # SSH public key — the only way to log in since password
    # auth is disabled in configuration.nix.
    openssh.authorizedKeys.keys = [ cfg.sshPubKey ];
  };

  # Allow wheel group members to use sudo without a password.
  # Required since password auth is disabled.
  security.sudo.wheelNeedsPassword = false;

  # -- SSH Host Key --
  # A stable host key is baked into the image so the fingerprint never
  # changes across re-provisions. Without this, every flash triggers a
  # "REMOTE HOST IDENTIFICATION HAS CHANGED" warning on connecting clients.
  environment.etc."ssh/ssh_host_ed25519_key" = {
    mode = "0600";
    text = cfg.hostKey;
  };
  environment.etc."ssh/ssh_host_ed25519_key.pub" = {
    text = cfg.hostKeyPub;
  };
  services.openssh.hostKeys = [
    { type = "ed25519"; path = "/etc/ssh/ssh_host_ed25519_key"; }
  ];

  # -- WiFi Configuration --
  # cfg.wifi is a list of { ssid, password } objects.
  # We use map + listToAttrs to convert the list into the
  # attrset that ensureProfiles.profiles expects, keyed by SSID.
  #
  # map transforms each element of a list:
  #   map (item: ...) list  →  new list
  #
  # listToAttrs converts a list of { name, value } pairs into
  # an attrset:
  #   listToAttrs [ { name = "a"; value = 1; } ]  →  { a = 1; }
  networking.networkmanager.ensureProfiles.profiles = builtins.listToAttrs (
    map (network: {
      name = network.ssid;
      value = {
        connection = {
          id = network.ssid;
          type = "wifi";
          autoconnect = true;
          autoconnect-priority = 100;
        };
        wifi = {
          ssid = network.ssid;
          mode = "infrastructure";
        };
        wifi-security = {
          key-mgmt = "wpa-psk";
          psk = network.password;
        };
        ipv4.method = "auto";
        ipv6.method = "auto";
      };
    }) cfg.wifi
  );
}
